extends Reference

var debug_failed = preload("res://addons/WAT/assets/debug_failed.png")
var docs = preload("res://addons/WAT/assets/docs.svg")
var failed = preload("res://addons/WAT/assets/failed.png")
var folder = preload("res://addons/WAT/assets/folder.png")
var function = preload("res://addons/WAT/assets/function.png")
var issue = preload("res://addons/WAT/assets/issue.svg")
var kofi = preload("res://addons/WAT/assets/kofi.png")
var label = preload("res://addons/WAT/assets/label.png")
var passed = preload("res://addons/WAT/assets/passed.png")
var play = preload("res://addons/WAT/assets/play.png")
var play_debug = preload("res://addons/WAT/assets/play_debug.png")
var play_failed = preload("res://addons/WAT/assets/play_failed.png")
var request_docs = preload("res://addons/WAT/assets/request_docs.svg")
var scriptx = preload("res://addons/WAT/assets/script.png")
var timer = preload("res://addons/WAT/assets/timer.png")
